### ISSUE TITLE
Contributions

### ISSUE THREAD

**Issue by Omkaragrawal** [bdcorps/candymail#14]
Hey,
Are you open to contributions?
I forked and cloned the repository, but the tests fail on the newly forked repo, can you line out how can I start contributing? I am sure that I can help you with adding different mail providers and some other stuffs.

Do let me know, can contact me on omkar3654@gmail.com or <a href="https://omkaragrawal.dev">website</a>

**Comment by bdcorps** [comment]
Hey Omkar, yes we are open for contributions. I'll add a guide shortly.

**Comment by bdcorps** [comment]
Added the `contributing.md` and a Project Roadmap for the issues that need to be completed for the next release [here](https://github.com/bdcorps/candymail/wiki/Project-Roadmap). Feel free to pick any of them up and I can assign it to you officially.
