### ISSUE TITLE
Add date-fns

### ISSUE THREAD

**Issue by Minho-Lee** [bdcorps/candymail#19]
In order to be consistent and easily scalable, might want to consider using [date-fns](https://date-fns.org/).

**Comment by bdcorps** [comment]
What's the comparison between date-fns and moment?

**Comment by Minho-Lee** [comment]
Well, `moment` was nice when it lasted. It's no longer going to be developed, only maintained, making it considered legacy.

Here's their official statement: https://momentjs.com/docs/#/-project-status/
