### ISSUE TITLE
Validate config using joi

### ISSUE THREAD

**Issue by bdcorps** [bdcorps/candymail#2]

**Comment by Omkaragrawal** [comment]
Hey, I'll take this one up, I'll use Validator instead of joi, I find it better at many fronts.

**Comment by bdcorps** [comment]
Just to add some context, the `config.js` file contains  `senderEmail`, `senderPassword`, and `hostingURL` that need to be set for the library to work correctly.

**Comment by Omkaragrawal** [comment]
Hey,
Checkout my pull request #18
