### ISSUE TITLE
Add more email providers

### ISSUE THREAD

**Issue by bdcorps** [bdcorps/candymail#7]

**Comment by Omkaragrawal** [comment]
Hey I'll take this one too.

**Comment by bdcorps** [comment]
This one is on hold for a bit before we figure out what providers would be appropriate. Most have free plans and transactional email support.

 Any suggestions are welcome!

**Comment by Omkaragrawal** [comment]
Hey,
Checkout my pull request #18

**Comment by bdcorps** [comment]
I agree that the dev should be able to use whichever service they would like to send messages over SMTP but from a library perspective, we should officially support only a select few. This is so we can manage the expectations and deal with bug issues that might come our way in the future. There will also need to be docs, examples needed. 

Let's make our priority to add two providers - Gmail (for quick testing), Amazon SES (for production workflow).

**Comment by Omkaragrawal** [comment]
Hey,
There's a misunderstanding here, it's not like we have to support those, those are already supported by node mailer, we are just letting the user know that it is supported. These options are there in the node mailer for a long time. So there is no reason to worry about it.
